import { useId } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Svg, { Defs, G, LinearGradient, Path, Stop } from 'react-native-svg';

import { colors, fonts } from '@/lib/theme';

// Generated by scripts/brand/mark.py (1024 design space): an "R" whose counter is a play button.
const BODY =
  'M292 246A34 34 0 0 1 326 212L566 212L582.82 212.73L599.51 214.93L615.95 218.58L632.01 223.64L647.57 230.08L662.5 237.86L676.7 246.9L690.06 257.15L702.47 268.53L713.85 280.94L724.1 294.3L733.14 308.5L740.92 323.43L747.36 338.99L752.42 355.05L756.07 371.49L758.27 388.18L759 405L758.27 421.82L756.07 438.51L752.42 454.95L747.36 471.01L740.92 486.57L733.14 501.5L724.1 515.7L713.85 529.06L702.47 541.47L690.06 552.85L676.7 563.1L662.5 572.14L647.57 579.92L632.01 586.36L615.95 591.42L599.51 595.07L582.82 597.27L566 598L452 598L452 786A26 26 0 0 1 426 812L326 812A34 34 0 0 1 292 778L292 246Z' +
  'M458 344.8A22 22 0 0 1 490.87 325.68L596.81 385.87A22 22 0 0 1 596.81 424.13L490.87 484.32A22 22 0 0 1 458 465.2L458 344.8Z';
const LEG =
  'M524.09 530L692.09 530L761.18 773.82A30 30 0 0 1 732.32 812L622.14 812A24 24 0 0 1 599.05 794.54L524.09 530Z';

/** Tight box around the mark, with a little room for antialiasing. */
const TIGHT = { x: 282, y: 202, w: 500, h: 620 };

interface MarkProps {
  /** Height in points. */
  size: number;
  /**
   * Draw on the full square canvas used by the splash screen image, so the
   * in-app intro can start exactly where the native splash leaves off.
   */
  splashFrame?: boolean;
  /** Single flat colour instead of the brand gradient. */
  color?: string;
}

export function LogoMark({ size, splashFrame, color }: MarkProps) {
  const id = useId().replace(/[^a-zA-Z0-9_-]/g, '');
  const viewBox = splashFrame ? '0 0 1024 1024' : `${TIGHT.x} ${TIGHT.y} ${TIGHT.w} ${TIGHT.h}`;
  const width = splashFrame ? size : (size * TIGHT.w) / TIGHT.h;

  return (
    <Svg width={width} height={size} viewBox={viewBox}>
      <Defs>
        <LinearGradient id={`${id}ink`} x1="300" y1="200" x2="780" y2="820" gradientUnits="userSpaceOnUse">
          <Stop offset="0" stopColor="#FF3D6E" />
          <Stop offset="0.48" stopColor="#FF2447" />
          <Stop offset="1" stopColor="#FF8A1F" />
        </LinearGradient>
        <LinearGradient id={`${id}leg`} x1="560" y1="530" x2="720" y2="812" gradientUnits="userSpaceOnUse">
          <Stop offset="0" stopColor="#C4133A" />
          <Stop offset="0.55" stopColor="#FF4A2E" />
          <Stop offset="1" stopColor="#FFA41F" />
        </LinearGradient>
        <LinearGradient id={`${id}fold`} x1="560" y1="588" x2="600" y2="718" gradientUnits="userSpaceOnUse">
          <Stop offset="0" stopColor="#000" stopOpacity="0.55" />
          <Stop offset="1" stopColor="#000" stopOpacity="0" />
        </LinearGradient>
        <LinearGradient id={`${id}sheen`} x1="292" y1="212" x2="560" y2="520" gradientUnits="userSpaceOnUse">
          <Stop offset="0" stopColor="#fff" stopOpacity="0.28" />
          <Stop offset="1" stopColor="#fff" stopOpacity="0" />
        </LinearGradient>
      </Defs>
      <G transform={splashFrame ? 'translate(-20 0)' : undefined}>
        {color ? (
          <>
            <Path d={LEG} fill={color} />
            <Path d={BODY} fill={color} fillRule="evenodd" />
          </>
        ) : (
          <>
            <Path d={LEG} fill={`url(#${id}leg)`} />
            <Path d={LEG} fill={`url(#${id}fold)`} />
            <Path d={BODY} fill={`url(#${id}ink)`} fillRule="evenodd" />
            <Path d={BODY} fill={`url(#${id}sheen)`} fillRule="evenodd" />
          </>
        )}
      </G>
    </Svg>
  );
}

/** The mark followed by "RANJHA PLAY". `size` is the mark height. */
export function Wordmark({ size, stacked }: { size: number; stacked?: boolean }) {
  const text = Math.round(size * (stacked ? 0.42 : 0.62));
  return (
    <View
      style={[styles.row, stacked && styles.stacked, { gap: size * (stacked ? 0.28 : 0.22) }]}
      accessible
      accessibilityRole="header"
      accessibilityLabel="Ranjha Play"
    >
      <LogoMark size={size} />
      <Text style={[styles.text, { fontSize: text, lineHeight: text * 1.1, letterSpacing: text * 0.06 }]}>
        RANJHA<Text style={styles.play}> PLAY</Text>
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center' },
  stacked: { flexDirection: 'column' },
  text: { color: colors.text, fontFamily: fonts.black, includeFontPadding: false },
  play: { color: colors.accent },
});
